### ISSUE TITLE
Figure out .env.express file for integration with package rate

### ISSUE THREAD

**Issue by priyankapereira1** [ECE-461-Project/ECE461_Project_Part2#58]
Logging setup for part1 code and Github token access is currently set in .env.express file locally. How to change this?

**Comment by just007in** [comment]
Current idea: set logging setup in .env.express. GITHUB_TOKEN is set in .env

.env.express can be committed to the github safely AS LONG AS GITHUB_TOKEN is not set in it.
.env will NOT be committed to the github and will be ignored in the .gitignore. The GITHUB_TOKEN should be acquired and set manually locally
